# Generated by Django 6.0.5 on 2026-05-30 05:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('checkmate', 'Checkmate'), ('stalemate', 'Stalemate'), ('timeout', 'Timeout'), ('resigned', 'Resigned'), ('draw', 'Draw')], default='active', max_length=20)),
                ('winner', models.CharField(blank=True, max_length=10, null=True)),
                ('white_player', models.CharField(default='Player 1', max_length=100)),
                ('black_player', models.CharField(default='Player 2', max_length=100)),
                ('time_control', models.IntegerField(default=10)),
                ('increment', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_state_data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('piece', models.CharField(max_length=20)),
                ('from_square', models.CharField(max_length=2)),
                ('to_square', models.CharField(max_length=2)),
                ('captured', models.CharField(blank=True, max_length=20, null=True)),
                ('special', models.CharField(blank=True, max_length=20, null=True)),
                ('time_spent', models.FloatField(default=0.0)),
                ('timestemp', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='api.game')),
            ],
            options={
                'ordering': ['move_number'],
            },
        ),
    ]
